name = "calculator"
description = ""
version = "0.1.0-dev"

authors = ["Arman"]
maintainers = ["Arman <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["calculator"]

[[depends-on]]
gtkada = "^26.0.0"

[[depends-on]]
gnatprove = "^15.1.0"
